# Warning - this file is autogenerated by the configure script
# Do not edit
VARDIR=/var/lib/xcp
VARPATCHDIR=/var/lib/xcp/patch
ETCDIR=/etc/xcp
OPTDIR=/usr/lib/xcp
PLUGINDIR=/usr/lib/xcp/plugins
HOOKSDIR=/etc/xcp/hook-scripts
XAPICONF=/etc/xcp/xapi.conf
RRDDCONF=/etc/xcp/rrdd.conf
LIBEXECDIR=/usr/lib/xcp/lib
SCRIPTSDIR=/usr/lib/xcp/scripts
SHAREDIR=/usr/share/xcp
WEBDIR=/var/www/html
XHADIR=/opt/xensource/xha
BINDIR=/usr/bin
SBINDIR=/usr/sbin
UDEVDIR=/lib/udev
